### ISSUE TITLE
RangeError exception on Smaller Candles Sizes 

### ISSUE THREAD

**Issue by caokietbk** [r-mzy47/candlesticks#15]
Hi @r-mzy47,

I am having the same problem with [#3] in version 2.1.0.

======== Exception caught by widgets library =======================================================
The following RangeError was thrown building TimeRow(dirty, state: _TimeRowState#3ab16):
RangeError (index): Invalid value: Not in inclusive range 0..10: 13
My candlesticks data:
[
{
date: 2022-04-17 23:00:00.000,
high: 40444.68,
low: 40167.07,
open: 40441.43,
close: 40167.07,
volume: 0.31,
},
{
date: 2022-04-18 00:00:00.000,
high: 40248.44,
low: 40025.83,
open: 40139.87,
close: 40063.51,
volume: 0.31,
},
{
date: 2022-04-18 01:00:00.000,
high: 40115.37,
low: 39849.07,
open: 40074.19,
close: 40088.32,
volume: 0.3,
},
{
date: 2022-04-18 02:00:00.000,
high: 40416.11,
low: 40061.47,
open: 40070.36,
close: 40343.83,
volume: 0.31,
},
{
date: 2022-04-18 03:00:00.000,
high: 40421.44,
low: 40220.83,
open: 40370.33,
close: 40238.37,
volume: 0.3,
},
{
date: 2022-04-18 04:00:00.000,
high: 40259.17,
low: 40095.77,
open: 40237.88,
close: 40178.74,
volume: 0.32,
},
{
date: 2022-04-18 05:00:00.000,
high: 40301.75,
low: 39895.45,
open: 40180.5,
close: 39964.25,
volume: 0.3,
},
{
date: 2022-04-18 06:00:00.000,
high: 39960.45,
low: 39511.67,
open: 39958.12,
close: 39656.38,
volume: 0.29,
},
{
date: 2022-04-18 07:00:00.000,
high: 39732.64,
low: 39546.85,
open: 39636.84,
close: 39701.03,
volume: 0.3,
},
{
date: 2022-04-18 08:00:00.000,
high: 39792.9,
low: 39630.19,
open: 39681.94,
close: 39721.78,
volume: 0.27,
},
{
date: 2022-04-18 09:00:00.000,
high: 39912.2,
low: 39700.37,
open: 39706.27,
close: 39768.48,
volume: 0.25,
}
]

**Comment by r-mzy47** [comment]
Hi @caokietbk
thanks for your report. I haven't tested this test case before, witch the count of candles is less than 32. If you have a deadline I will find a quick solution for it. otherwise, I will fix this issue in the next version in a few days.

**Comment by caokietbk** [comment]
> Hi @caokietbk thanks for your report. I haven't tested this test case before, witch the count of candles is less than 32. If you have a deadline I will find a quick solution for it. otherwise, I will fix this issue in the next version in a few days.

I have a deadline on April 22, so I'll be very grateful if you can fix it before that day.
If you are too busy, I can wait for your stable solution to it.
Thank you very much. 😇
