### ISSUE TITLE
Issue on price pointer indicator for mobile

### ISSUE THREAD

**Issue by christenbc** [r-mzy47/candlesticks#25]
I created a horizontal indicator to determine some levels

```
class HorizontalLineIndicator extends Indicator {
  HorizontalLineIndicator({
    required String title,
    required double value,
    Color? color,
  }) : super(
          name: '$title on $value',
          dependsOnNPrevCandles: 0,
          calculator: (index, candles) => [value],
          indicatorComponentsStyles: [
            IndicatorStyle(name: "ind", color: color ?? Colors.blue),
          ],
        );
}
```
This way I realized there are some mismatches between price marks.

---

**Case: See the web app pointer price indicator.** It marks almost 19400. This is correctly matching.

<img width="1128" alt="issue1" src="https://user-images.githubusercontent.com/45597426/196011369-e4a83e03-7fca-4e97-b86c-ae8757fbe6ea.png">

---

**Case: See the mobile app pointer price indicator.** It marks around 19378. Which is wrong and should indicate 19400 instead.

<img width="1127" alt="issue2" src="https://user-images.githubusercontent.com/45597426/196011371-45db9e6e-0355-4bbb-8759-b88c2e465c94.png">

---

**Case: See the mobile app pointer price indicator.** The pointer price mark around 19400 is noticeably above the horizontal indicator around the value 19400.

<img width="1126" alt="issue3" src="https://user-images.githubusercontent.com/45597426/196011373-7d771dbc-1d90-425e-a21f-36bf24ceba16.png">

**Comment by christenbc** [comment]
@r-mzy47 may I know the reason this was closed?

**Comment by r-mzy47** [comment]
fixed with [this](https://github.com/r-mzy47/candlesticks/commit/7f652351a3fa95db77fa21cd92f189a53c29462a) commit

**Comment by christenbc** [comment]
Wonderful, good job
