### ISSUE TITLE
The text color of Auto button is not visible

### ISSUE THREAD

**Issue by christenbc** [r-mzy47/candlesticks#26]
The text color of Auto button is not visible

![issue4](https://user-images.githubusercontent.com/45597426/196011781-9e4d0e41-e8d6-41da-a147-46e0c3c5128f.jpg)

**Comment by christenbc** [comment]
@r-mzy47 may I know the reason this was closed?

**Comment by r-mzy47** [comment]
fixed with [this](https://github.com/r-mzy47/candlesticks/commit/899fa3c18bcb6b050a205c35155c64e31d4918bc) commit

**Comment by christenbc** [comment]
Great! Thanks for the answer and the fix
