### ISSUE TITLE
Out of Bounds on Smaller Candles Sizes

### ISSUE THREAD

**Issue by mmmtastymmm** [r-mzy47/candlesticks#3]
If I make a smaller dataset, like by using this for loop, I get out of bounds issues with the grapher. This is on windows.
```dart
List<Candle> getCandles(){
  final List<Candle> output = [];
  final time = DateTime.now();
  for (int i = 0; i < 10; i++){
    output.add(Candle(open: 1700 + i*20, high: 1800 + i * 20 + 0.0000001, low: 1700 + i * 10-0.00011, close: 1800 + i * 10, volume: 1.0 * i, date: time.subtract(Duration(days: 1 * i))));
  }
  return output;
}
```
![image](https://user-images.githubusercontent.com/69337696/124521732-d9515980-ddad-11eb-9c7d-21fc78d84ad1.png)

If I increase that for loop to 1000 or so it doesn't appear.

My current hack is to do this in the time_row.dart file.
```dart
//int candleNumber = (step + 1) ~/ 2 - 10 + index * step + -1;
int candleNumber = index;
```

**Comment by stormqueen23** [comment]
Same problem here. But it is not related to the size. 
I have a loop with 2000 entries and if I scroll to the end of the chart the same error appears

**Comment by mmmtastymmm** [comment]
Yeah you are right, that happens with me too.

**Comment by mg7237** [comment]
I am facing the same issue. Is there any support on this package or we should look for alternate option?

**Comment by mg7237** [comment]
I have moved to https://pub.dev/packages/syncfusion_flutter_charts

They provide easy to follow video https://help.syncfusion.com/flutter/cartesian-charts/chart-types/candle-chart?_ga=2.183977071.878455877.1626833079-218761931.1626833079

**Comment by r-mzy47** [comment]
Fixed in 1.0.0 version. Sorry for the delay.
Best regards :)

**Comment by hm122** [comment]
Having the same problem. When zooming in or out the RangeError appears.
<img width="343" alt="Screen Shot 2021-11-24 at 11 21 59" src="https://user-images.githubusercontent.com/13405226/143220328-3a462994-06a5-4fd8-8b10-39e1b9125080.png">

**Comment by caokietbk** [comment]
Having some problem in version 2.1.0.
======== Exception caught by widgets library =======================================================
The following RangeError was thrown building TimeRow(dirty, state: _TimeRowState#3ab16):
RangeError (index): Invalid value: Not in inclusive range 0..10: 13
My candlesticks data:
[
{
          date: 2022-04-17 23:00:00.000,
          high: 40444.68,
          low: 40167.07,
          open: 40441.43,
          close: 40167.07,
          volume: 0.31,
},
{
          date: 2022-04-18 00:00:00.000,
          high: 40248.44,
          low: 40025.83,
          open: 40139.87,
          close: 40063.51,
          volume: 0.31,
},
{
          date: 2022-04-18 01:00:00.000,
          high: 40115.37,
          low: 39849.07,
          open: 40074.19,
          close: 40088.32,
          volume: 0.3,
},
{
          date: 2022-04-18 02:00:00.000,
          high: 40416.11,
          low: 40061.47,
          open: 40070.36,
          close: 40343.83,
          volume: 0.31,
},
{
          date: 2022-04-18 03:00:00.000,
          high: 40421.44,
          low: 40220.83,
          open: 40370.33,
          close: 40238.37,
          volume: 0.3,
},
{
          date: 2022-04-18 04:00:00.000,
          high: 40259.17,
          low: 40095.77,
          open: 40237.88,
          close: 40178.74,
          volume: 0.32,
},
{
          date: 2022-04-18 05:00:00.000,
          high: 40301.75,
          low: 39895.45,
          open: 40180.5,
          close: 39964.25,
          volume: 0.3,
},
{
          date: 2022-04-18 06:00:00.000,
          high: 39960.45,
          low: 39511.67,
          open: 39958.12,
          close: 39656.38,
          volume: 0.29,
},
{
          date: 2022-04-18 07:00:00.000,
          high: 39732.64,
          low: 39546.85,
          open: 39636.84,
          close: 39701.03,
          volume: 0.3,
},
{
          date: 2022-04-18 08:00:00.000,
          high: 39792.9,
          low: 39630.19,
          open: 39681.94,
          close: 39721.78,
          volume: 0.27,
},
{        
          date: 2022-04-18 09:00:00.000,
          high: 39912.2,
          low: 39700.37,
          open: 39706.27,
          close: 39768.48,
          volume: 0.25,
}
]
