### ISSUE TITLE
Intervals choose

### ISSUE THREAD

**Issue by wedersonrsouza** [r-mzy47/candlesticks#4]
Is it possible to choose which graphic ranges we want to make available?

**Comment by r-mzy47** [comment]
What do you mean by "graphic ranges". Could you please explain more?

**Comment by wedersonrsouza** [comment]
graphic ranges = intervals (1w, 1d, 1hour,  1min)

Sorry about my English

**Comment by r-mzy47** [comment]
check out new version 1.0.1 
[Candlesticks] widget now accepts an optional parameter named 'intervals'
