### ISSUE TITLE
How do we style the candlesticks?

### ISSUE THREAD

**Issue by AlthafAslam** [r-mzy47/candlesticks#9]
Can you please guide me to style the Default Candles . I was trying to be add a little padding around each of the candles. Can you please guide me to achieve this?

**Comment by r-mzy47** [comment]
Hi @AlthafAslam. unfortunately, this feature is not available through APIs. but you can change a few lines of the package to achieve your goal.
kindly replace `..strokeWidth = _barWidth - 1` with `..strokeWidth = _barWidth - NEWPADDING * 2` in https://github.com/r-mzy47/candlesticks/blob/develop/lib/src/widgets/volume_widget.dart: 
and in https://github.com/r-mzy47/candlesticks/blob/develop/lib/src/widgets/candle_stick_widget.dart: replace `paint..strokeWidth = _candleWidth - 1` lines  with `paint..strokeWidth = _candleWidth - NEWPADDING * 2`.
